---
- name: Create terminator config folder
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/terminator/"
    state: directory
    mode: 0744
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Copy terminator config
  ansible.builtin.copy:
    src: terminatorConfig
    dest: "{{ ansible_user_dir }}/.config/terminator/config"
    mode: 0744
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    backup: true