---
- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Add the flathub flatpak repository remote to the system installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system
  become: true

- name: Install flatpaks
  community.general.flatpak:
    name:
      - com.github.tchx84.Flatseal
      - com.mattjakeman.ExtensionManager
      - com.spotify.Client
      - com.vscodium.codium
      - md.obsidian.Obsidian
      - org.signal.Signal
      - org.videolan.VLC
      - org.mozilla.firefox
      - com.brave.Browser
      - com.rustdesk.RustDesk
      - org.remmina.Remmina
      - org.freedesktop.Platform.ffmpeg-full/x86_64/24.08
      - org.onlyoffice.desktopeditors
    method: user

- name: Remove the fedora flatpak repository remote to the system installation
  community.general.flatpak_remote:
    name: fedora
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system
