---
- name: Create distrobox containers
  ansible.builtin.shell:
    cmd: yes | distrobox create -n "{{ item }}" -i fedora:42
  loop:
    - fwsbox
  changed_when: false

- name: Install packages in fwsbox container
  become: no
  ansible.builtin.shell:
    cmd: /usr/bin/distrobox enter fwsbox -- sh -c 'sudo dnf install -y "{{ item }}"'
  loop:
    - tldr
    - tmux
    - tree
    - dua-cli
    - which
    - feh
  changed_when: false

- name: Export packages in fwsbox container
  become: no
  ansible.builtin.shell:
    cmd: /usr/bin/distrobox enter fwsbox -- sh -c 'distrobox-export -b /usr/bin/"{{ item }}" -ep $HOME/.local/bin'
  loop:
    - tldr
    - tmux
    - tree
    - dua
    - feh
  changed_when: false

# - name: Export packages in fwsbox container
#   become: no
#   ansible.builtin.shell:
#     cmd: /usr/bin/distrobox enter fwsbox -- sh -c "{{ item }}"
#   loop:
#     - "distrobox-export -b /usr/bin/htop -ep $HOME/.local/bin"
#     - "distrobox-export -b /usr/bin/tldr -ep $HOME/.local/bin"
#     - "distrobox-export -b /usr/bin/tmux -ep $HOME/.local/bin"
#     - "distrobox-export -b /usr/bin/tree -ep $HOME/.local/bin"
#     - "distrobox-export -b /usr/bin/dua -ep $HOME/.local/bin"
#     - "distrobox-export -b /usr/bin/feh -ep $HOME/.local/bin"
#   changed_when: false
