---
- name: Create i3 config folder
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/i3/"
    state: directory
    mode: 0744
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Copy i3 config
  ansible.builtin.copy:
    src: i3config
    dest: "{{ ansible_user_dir }}/.config/i3/config"
    mode: 0744
    backup: true

#- name: add lxpolkit to i3config
#  ansible.builtin.lineinfile:
#  insertafter: '^exec --no-startup-id dex-autostart --autostart --environment i3'
#  state: present
#  line: |
#    # Launch lxpolkit
#    exec_always --no-startup-id lxpolkit &