---
- name: Create i3 config folder
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/i3/"
    state: directory
    mode: 0744
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Copy i3 config
  ansible.builtin.copy:
    src: i3config
    dest: "{{ ansible_user_dir }}/.config/i3/config"
    mode: 0744
    backup: true

- name: Create picom config folder
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/picom/"
    state: directory
    mode: 0744
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Copy picom config
  ansible.builtin.copy:
    src: picomConfig
    dest: "{{ ansible_user_dir }}/.config/picom/picom.conf"
    mode: 0744
    backup: true

- name: Create Wallpapers config folder
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/Pictures/Wallpapers"
    state: directory
    mode: 0744
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"